name: Deploy to Cloud Run
# https://github.com/google-github-actions/example-workflows/blob/main/workflows/deploy-cloudrun/cloudrun-docker.yml
on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'

      # https://github.com/google-github-actions/auth
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'cloud-run-admin@dynamic-vehicle-380810.iam.gserviceaccount.com'


      # https://github.com/google-github-actions/setup-gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      
      - name: Build and push Docker image
      # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/nextjs:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nextjs \
            --image gcr.io/${{ secrets.PROJECT_ID }}/nextjs:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
